<?php

use \Drupal\vr_base\VrBase;
use \Drupal\Core\Form\FormStateInterface;

function vr_base_form_vr_hotspot_base_hotspot_form_alter (&$form, FormStateInterface $form_state) {
  if(VrBase::formIsAjax($form_state) && VrBase::formHasArgs($form_state)) {
    $form['#prefix'] = '<div id="'.VrBase::formWrapper.'">';
    $form['#suffix'] = '</div>';
    $form['field_pitch']['widget'][0]['value']['#default_value'] = $form_state->get('pitch');
    $form['field_yaw']['widget'][0]['value']['#default_value'] = $form_state->get('yaw');
    $form['actions']['submit']['#ajax'] = [ 'callback' => '\Drupal\vr_base\Controller\ModalFormHotSpotController::formAjaxCallback'];
  }
}
